name: "Next Action Workflow"

env:
  NODE_ENV: production
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

on:
  pull_request:
    branches: [opened, synchronize, reopened]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "**/*.jsx"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v6
        with:
          node-version: 24
      - run: corepack enable
        with:
          cache: yarn
      - run: yarn install --immutable

      - name: Run linter
        run: yarn lint

  preview:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Install dependencies
        uses: actions/checkout@v6
        with:
          node-version: 24
          cache: yarn
      - run: corepack enable
      - run: yarn install --immutable

      - name: Build application
        run: yarn build

      - name: Deploy preview
        run: yarn deploy:prod

  test-e2e:
    runs-on: ubuntu-latest
    needs: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          node-version: 24
          cache: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: chrome

      - run: corepack enable
      - run: yarn install --immutable
